### ISSUE TITLE
DNS

### ISSUE THREAD

**Issue by vinicius-a-almeida** [vinicius-a-almeida/network-metrics#1]
Alterar o código para ser em millisegundos

**Comment by walberjose** [comment]
Como você está usando o curl, ele irá trazer os valores em segundos mas na notação de ponto flutuante. No manpage do curl, https://curl.se/docs/manpage.html, há várias variáveis interessantes para serem adicionadas ao script:

- - speed_download: The average download speed that curl measured for the complete download. Bytes per second. 
- - speed_upload: The average upload speed that curl measured for the complete upload. Bytes per second. 
- - time_appconnect: The time, in seconds, it took from the start until the SSL/SSH/etc connect/handshake to the remote host was completed. 
- time_connect: The time, in seconds, it took from the start until the TCP connect to the remote host (or proxy) was completed.
- time_namelookup: The time, in seconds, it took from the start until the name resolving was completed.
- time_posttransfer: The time it took from the start until the last byte is sent by libcurl. In microseconds. (Added in 8.10.0)
- time_pretransfer: The time, in seconds, it took from the start until the file transfer was just about to begin. This includes all pre-transfer commands and negotiations that are specific to the particular protocol(s) involved.
- time_redirect: The time, in seconds, it took for all redirection steps including name lookup, connect, pretransfer and transfer before the final transaction was started. "time_redirect" shows the complete execution time for multiple redirections.
- time_starttransfer: The time, in seconds, it took from the start until the first byte is received. This includes time_pretransfer and also the time the server needed to calculate the result.
- time_total: The total time, in seconds, that the full operation lasted.
